import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.5)",
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 9999,
    },
    emptyContainer: {
        flex: 1,
        backgroundColor: "white",
        alignItems: "center",
        width: "100%",
    },
    emptyContainerInner: {
        width: "100%",
    },
    statusBarContainer: {
        height: 40,
        backgroundColor: '#0066B1',
    },
    topBar: {
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "#0066B1",
        height: 60,
        alignItems: "center",
        padding: 10,
    },
    logo: {
        width: 100,
        height: 100,
        resizeMode: "contain",
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "white",
    },
    emptyCartImage: {
        width: "50%",
        height: "50%",
    },
    container: {
        flex: 1,
        alignItems: "center",
        backgroundColor: "white",
        width: "100%",
    },
    containerInner: {
        flex: 1,
        width: "100%",
    },
    topBarRow: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
    },
    basketIcon: {
        width: 30,
        height: 30,
        tintColor: "white",
    },
    basketTitle: {
        fontSize: 20,
        fontWeight: "bold",
        marginLeft: 10,
        color: "white",
    },
    clearCartBtn: {
        padding: 7,
        paddingLeft: 15,
        paddingRight: 15,
        borderWidth: 2,
        borderColor: "white",
        borderRadius: 50,
    },
    clearCartBtnText: {
        fontSize: 18,
        color: "white",
    },
    cartContainer: {
        flex: 1,
        width: "100%",
    },
    itemContainer: {
        height: 80,
        width: "100%",
        backgroundColor: "white",
    },
    items: {
        width: "100%",
        height: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 10,
        backgroundColor: "white",
        borderBottomWidth: 1,
        borderBottomColor: "#e6e6e6",
    },
    imageContainer: {
        width: "20%",
    },
    image: {
        width: "100%",
        height: "100%",
        resizeMode: "contain",
    },
    itemDetails: {
        width: "60%",
        height: "100%",
        flexDirection: "column",
        justifyContent: "space-between",
    },
    itemName: {
        color: "black",
        fontSize: 16,
        fontWeight: "bold",
    },
    qtyBtn: {},
    qtyRow: {
        width: "40%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    qtyLabel: {
        fontSize: 16,
        color: "black",
    },
    qtyBtnText: {
        color: "black",
        fontSize: 14,
        fontWeight: "bold",
    },
    itemPriceContainer: {
        top: 20,
        width: "16%",
        textAlign: "right",
    },
    itemPrice: {
        color: "black",
        fontWeight: "bold",
        textAlign: "right",
    },
    bottomView: {
        width: "95%",
        alignItems: "center",
        padding: 10,
    },
    cartTotal: {
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1.5,
        borderColor: "#0066B1",
        padding: 10,
        marginTop: 10,
        borderRadius: 50,
    },
    cartTotalText: {
        color: "#0066B1",
        fontSize: 16,
        fontWeight: "bold",
    },
    checkoutBtn: {
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#0066B1",
        padding: 10,
        marginTop: 10,
        borderRadius: 50,
    },
    checkoutBtnContainer: {},
    checkoutBtnText: {
        color: "white",
        fontSize: 18,
        fontWeight: "bold",
    },
    swipeDeleteContainer: {
        justifyContent: "center",
        alignItems: "center",
    },
    swipeDeleteBtn: {
        backgroundColor: "red",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        height: "100%",
        paddingLeft: 15,
        paddingRight: 15,
    },
    swipeDeleteIcon: {
        width: 30,
        height: 30,
    },
    dealItemContainer: {
        minHeight: 100,
        width: "100%",
        backgroundColor: "#FFF8E7",
    },
    dealItems: {
        width: "100%",
        minHeight: 100,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 10,
        backgroundColor: "#FFF8E7",
        borderBottomWidth: 1,
        borderBottomColor: "#FFD700",
        borderLeftWidth: 4,
        borderLeftColor: "#FF6B00",
    },
    dealBadge: {
        position: "absolute",
        top: 5,
        left: 5,
        backgroundColor: "#FF6B00",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 10,
        zIndex: 1,
    },
    dealBadgeText: {
        color: "white",
        fontSize: 10,
        fontWeight: "bold",
    },
    dealItemName: {
        color: "#333",
        fontSize: 16,
        fontWeight: "bold",
        marginTop: 15,
    },
    dealInfoRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 4,
    },
    dealProductCount: {
        fontSize: 12,
        color: "#666",
        marginRight: 10,
    },
    dealDiscount: {
        fontSize: 12,
        color: "#FF6B00",
        fontWeight: "bold",
    },
    dealItemPrice: {
        color: "#FF6B00",
        fontWeight: "bold",
        textAlign: "right",
        fontSize: 16,
    },
    dealOriginalPrice: {
        color: "#999",
        fontSize: 12,
        textAlign: "right",
        textDecorationLine: "line-through",
    },
})

export default styles
