import { Platform, StyleSheet } from 'react-native';

const COLORS = {
  primary: '#1946A9',
  background: '#FFFFFF',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  card: '#FFFFFF',
  cardBorder: '#E5E7EB',
  iconBg: '#EEF2FF',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textMuted,
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    overflow: 'visible',
    marginBottom: 20,
  },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cardBorder,
  },
  fieldRowLast: {
    borderBottomWidth: 0,
  },
  fieldIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: COLORS.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  fieldContent: {
    flex: 1,
    paddingRight: 4,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textMuted,
    letterSpacing: 0.6,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  fieldInput: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.textPrimary,
    padding: 0,
    margin: 0,
  },
  placesFieldRow: {
    alignItems: 'flex-start',
    paddingBottom: 8,
    zIndex: 1000,
    elevation: 10,
  },
  placesTextInputContainer: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 0,
    height: 'auto',
    marginTop: 0,
    marginBottom: 0,
    paddingHorizontal: 0,
  },
  placesTextInput: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.textPrimary,
    height: 24,
    margin: 0,
    padding: 0,
  },
  placesListView: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    position: 'absolute',
    top: 52,
    left: 0,
    right: 0,
    zIndex: 2000,
  },
  placesRow: {
    backgroundColor: COLORS.background,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 44,
  },
  placesDescription: {
    color: COLORS.textPrimary,
    fontSize: 14,
  },
  defaultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  defaultTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  defaultTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  defaultSubtitle: {
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: Platform.OS === 'ios' ? 28 : 20,
    backgroundColor: COLORS.background,
    borderTopWidth: 1,
    borderTopColor: COLORS.cardBorder,
  },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 16,
  },
  saveBtnDisabled: {
    opacity: 0.7,
  },
  saveBtnText: {
    color: COLORS.background,
    fontSize: 16,
    fontWeight: '700',
  },
});

export default styles;
